ci:
  autoupdate_schedule: monthly

exclude: qtpy/|test/fixtures/|\.rtf$|PkgInfo$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        name: Enforce Python 3.6 idioms
        args:
          - --py36-plus

  - repo: https://github.com/jsh9/cercis
    rev: 0.2.5
    hooks:
      - id: cercis
        args:
          - --line-length=88
          - --function-definition-extra-indent=False
